name: Test

on: [push, pull_request]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Dependancies
        run: |
          sudo apt-get update
          sudo apt-get install zsh
          mkdir $(pwd)/tests/.nvm
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | NVM_DIR="$(pwd)/tests/.nvm" bash
        if: matrix.os == 'ubuntu-latest'

      - name: Install Dependancies
        run: |
          brew update
          brew install zsh nvm
          brew uninstall node || true
        if: matrix.os == 'macos-latest'

      - name: Initialise
        run: |
          zsh --version
          sudo rm -rf /{usr/local,opt/homebrew}/{lib/node{,/.npm,_modules},bin,share/man}/{npm*,node*,man1/node*}
          if [[ $(command -v nvm) == "nvm" ]]; then nvm deactivate && nvm unload; fi
        
      - name: Install Urchin
        run: |
          (mkdir /tmp/urchin && cd /tmp/urchin && curl -s "$(curl -s https://registry.npmjs.com/urchin | grep -Eo '"tarball":\s*"[^"]+"' | tail -n 1 | awk -F\" '{ print $4 }')" -O && tar -x -f urchin*)
          chmod +x /tmp/urchin/package/urchin
        
      - name: Run tests
        run: |
          /tmp/urchin/package/urchin -s zsh tests
        