name: Update Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-fork:
    runs-on: ubuntu-latest
    outputs:
      new-commits: ${{ steps.change-check.outputs.NEW_COMMITS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git Info
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/lukechilds/zsh-nvm.git

      - name: Rebase
        run: |
          git fetch upstream
          git rebase upstream/master

      - name: Check for Changes
        id: change-check
        run: |
          git fetch origin
          echo "NEW_COMMITS=$([[ $(git rev-parse master) != $(git rev-parse origin/master) ]] && echo true || echo false)" >> "$GITHUB_OUTPUT"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
